eq_generator_bylag  <-  function(data,fspecs=fspecs,oprob = FALSE,use_EC = FALSE, setconst = TRUE, long=FALSE){
  #DESCRIPTION
  # eq_generator_bylag generates equations for the basic ratings / yields model. It can include country dummies, asymmetric effects, and contemporaneous effects
  #-------------------------------------------------------------------------------
  #USAGE
  # data_prep(data,lags_dyields,lags_dratings,oprob, rasym, yasym,factors,cdums)
  #-------------------------------------------------------------------------------
  #INPUT
  # data            data generated by data_prep.r. Needed to extract country dummies
  # fspecs          Structure controlling estimation setup
  # oprob           boolean if ordered probit equation
  # use_EC          boolean if error correction should be used instead of lagged yields (and facratings)
  # setconst        boolean if the constant should be included in the yield estimation.
  # long            boolean if lagterm should also be returned
  #-------------------------------------------------------------------------------
  #OUTPUT
  # formula string
  #-------------------------------------------------------------------------------
  #AUTHORS: Makram El-Shagi and Gregor von Schweinitz
  
  if (oprob){
    lags_dyields <- fspecs$rlags_y
    lags_dratings <- fspecs$rlags_r
  }
  else{
    lags_dyields <- fspecs$ylags_y
    lags_dratings <- fspecs$ylags_r
  }
  rasym <- fspecs$asym
  yasym <- fspecs$asym
  factors <- fspecs$factors
  cdums <- fspecs$cdums
  data <- cuttolags(data,max(lags_dyields),max(lags_dratings))
  cnames <- colnames(data)
  
  out <- mat.or.vec(max(lags_dyields),5)
  
  if (!oprob & cdums & !setconst) {
    warning("constant needed for linear estimation with cdums")
    return(NULL)
  }
  if (use_EC) {
    lagterm="EC"
    factors <- NULL
  } 
  else{
    lagterm = "lyields"
  }
  if (!oprob & setconst){lagterm <- c(lagterm,"const")}
  
  extras <- c("","_p","_n")
  
  if (!yasym) {run = 1} else {run = 2:3}
  for (r in run) {
    for (l in lags_dyields) {
      lagterm <- c(lagterm,paste("dyields",l,extras[r],sep=""))
    }
  }
  if (!rasym) {run = 1} else {run = 2:3}
  for (r in run) {
    for (l in lags_dratings) {
      lagterm <- c(lagterm,paste("dratings",l,extras[r],sep=""))
    }
  }
  
  if (oprob) {
      formula <- eq_generator("dratings0_fac",lagterm,factors = factors,countrydums=cdums,cnames=cnames,oprob=oprob)
  } else {
      formula <- eq_generator("dyields0",lagterm,factors = factors,countrydums=cdums,cnames=cnames,oprob=oprob)
  }
  
  print(formula)  
  if (long){
    out <- NULL
    out$formula <- formula
    out$lagterm <- lagterm
    return(out)
  }
  else{return(formula)}
}